# Generated by Django 5.0.2 on 2024-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(blank=True, choices=[('+2', '+2'), ('Diploma', 'Diploma'), ('BA ', 'BA'), ('BSc', 'BSc'), ('BCom', 'BCom'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('B.Tech', 'B.Tech'), ('B.Ed', 'B.Ed'), ('BFA', 'BFA'), ('MA', 'MA'), ('MSc', 'MSc'), ('Mcom', 'Mcom'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('M.Tech', 'M.Tech'), ('M.Ed', 'M.Ed'), ('MFA', 'MFA'), ('Ph.D', 'Ph.D')], max_length=20),
        ),
    ]
