# Generated by Django 5.0.2 on 2024-02-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_app', '0009_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
