# Generated by Django 5.0.2 on 2024-02-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_app', '0010_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('application', 'Application'), ('rejected_application', 'Rejected Application')], max_length=20),
        ),
    ]
